package cmd

import (
	"fmt"
	"io"
	"os"
)

// RunCompletion prints a shell-completion script for the requested shell to
// stdout. Returns a process exit code.
//
// netcheck doesn't use cobra (it uses the stdlib `flag` package), so the
// completion scripts are hand-written. They only complete the top-level
// subcommand name today — enough to get tab-complete on `netcheck d<TAB>` →
// `netcheck dns`. Flag completion (--output text|json|markdown|html,
// --config <path>, etc.) is not implemented; if/when someone asks, the
// natural upgrade is per-shell flag tables — not a cobra migration.
//
// Install one-liners (also in `netcheck completion --help`):
//
//	bash:        netcheck completion bash       > /etc/bash_completion.d/netcheck
//	zsh:         netcheck completion zsh        > "${fpath[1]}/_netcheck"
//	fish:        netcheck completion fish       > ~/.config/fish/completions/netcheck.fish
//	powershell:  netcheck completion powershell | Out-String | Invoke-Expression
func RunCompletion(args []string) int {
	if len(args) == 0 || args[0] == "-h" || args[0] == "--help" || args[0] == "help" {
		printCompletionUsage(os.Stderr)
		if len(args) == 0 {
			return 2
		}
		return 0
	}
	switch args[0] {
	case "bash":
		fmt.Print(bashCompletion)
	case "zsh":
		fmt.Print(zshCompletion)
	case "fish":
		fmt.Print(fishCompletion)
	case "powershell", "pwsh":
		fmt.Print(powershellCompletion)
	default:
		fmt.Fprintf(os.Stderr, "unknown shell %q\n\n", args[0])
		printCompletionUsage(os.Stderr)
		return 2
	}
	return 0
}

func printCompletionUsage(w io.Writer) {
	fmt.Fprintln(w, "usage: netcheck completion {bash|zsh|fish|powershell}")
	fmt.Fprintln(w)
	fmt.Fprintln(w, "Prints a shell-completion script for the requested shell to stdout.")
	fmt.Fprintln(w, "Pipe or redirect it into the right place for your shell:")
	fmt.Fprintln(w)
	fmt.Fprintln(w, "  bash (system-wide):")
	fmt.Fprintln(w, "    netcheck completion bash | sudo tee /etc/bash_completion.d/netcheck >/dev/null")
	fmt.Fprintln(w, "  bash (per-user):")
	fmt.Fprintln(w, "    netcheck completion bash > ~/.local/share/bash-completion/completions/netcheck")
	fmt.Fprintln(w)
	fmt.Fprintln(w, "  zsh (add a dir to fpath if needed):")
	fmt.Fprintln(w, `    netcheck completion zsh > "${fpath[1]}/_netcheck"`)
	fmt.Fprintln(w, "    # then in a fresh shell, autoload -Uz compinit && compinit")
	fmt.Fprintln(w)
	fmt.Fprintln(w, "  fish:")
	fmt.Fprintln(w, "    netcheck completion fish > ~/.config/fish/completions/netcheck.fish")
	fmt.Fprintln(w)
	fmt.Fprintln(w, "  powershell (current session only — add to $PROFILE to persist):")
	fmt.Fprintln(w, "    netcheck completion powershell | Out-String | Invoke-Expression")
}

// Keep this list in sync with cmd/root.go's main switch + runConfigCmd.
// Order matches usage() so the completion menu reads the same way the help
// does.
var completionSubcommands = []struct {
	name string
	desc string
}{
	{"menu", "interactive menu"},
	{"app", "run the local web app"},
	{"dns", "compare DNS resolvers"},
	{"route", "trace the network path with per-hop ASN"},
	{"ip", "show IP ownership, RDAP, reverse DNS, CDN hints"},
	{"headers", "security-header report card"},
	{"tech", "fingerprint CMS / framework / server / CDN"},
	{"subs", "enumerate subdomains via Certificate Transparency"},
	{"reverse", "other hostnames on this IP"},
	{"arch", "Wayback Machine snapshots"},
	{"whois", "registrar lookup via RDAP"},
	{"tls", "TLS protocol+cipher matrix audit (ACTIVE)"},
	{"takeover", "subdomain-takeover check on CNAME (ACTIVE)"},
	{"ports", "TCP connect scan (ACTIVE)"},
	{"enum", "HTTP path enumeration (ACTIVE)"},
	{"audit", "aggregate report (passive + optional active)"},
	{"config", "print active config"},
	{"completion", "print shell completion script"},
	{"help", "show help"},
	{"version", "show version"},
}

// bashCompletion: minimal, only completes the first positional. After that we
// fall through to bash's default filename completion, which is the right
// behaviour for `netcheck audit <target>` style invocations where the second
// arg is a hostname or URL (and bash can't introspect those anyway).
var bashCompletion = `# bash completion for netcheck — generated by ` + "`netcheck completion bash`" + `
_netcheck() {
    local cur prev
    COMPREPLY=()
    cur="${COMP_WORDS[COMP_CWORD]}"
    prev="${COMP_WORDS[COMP_CWORD-1]}"

    # Only complete the subcommand name (first positional).
    if [ "$COMP_CWORD" -eq 1 ]; then
        local cmds="menu app dns route ip headers tech subs reverse arch whois tls takeover ports enum audit config completion help version"
        COMPREPLY=( $(compgen -W "$cmds" -- "$cur") )
        return 0
    fi

    # Complete shell names after ` + "`netcheck completion`" + `.
    if [ "$COMP_CWORD" -eq 2 ] && [ "${COMP_WORDS[1]}" = "completion" ]; then
        COMPREPLY=( $(compgen -W "bash zsh fish powershell" -- "$cur") )
        return 0
    fi

    # Complete --output values.
    if [ "$prev" = "--output" ] || [ "$prev" = "-output" ]; then
        COMPREPLY=( $(compgen -W "text json markdown html" -- "$cur") )
        return 0
    fi

    # Otherwise leave it to bash's default (filenames, useful for --config etc).
    return 0
}
complete -F _netcheck netcheck
`

// zshCompletion: uses zsh's _describe so each subcommand shows with a short
// description in the menu. Slightly nicer UX than the bash version.
var zshCompletion = `#compdef netcheck
# zsh completion for netcheck — generated by ` + "`netcheck completion zsh`" + `

_netcheck() {
    local -a subcmds
    subcmds=(
        'menu:interactive menu'
        'app:run the local web app'
        'dns:compare DNS resolvers'
        'route:trace the network path with per-hop ASN'
        'ip:IP ownership, RDAP, reverse DNS, CDN hints'
        'headers:security-header report card'
        'tech:fingerprint CMS / framework / server / CDN'
        'subs:enumerate subdomains via Certificate Transparency'
        'reverse:other hostnames on this IP'
        'arch:Wayback Machine snapshots'
        'whois:registrar lookup via RDAP'
        'tls:TLS protocol+cipher matrix audit (ACTIVE)'
        'takeover:subdomain-takeover check on CNAME (ACTIVE)'
        'ports:TCP connect scan (ACTIVE)'
        'enum:HTTP path enumeration (ACTIVE)'
        'audit:aggregate report (passive + optional active)'
        'config:print active config'
        'completion:print shell completion script'
        'help:show help'
        'version:show version'
    )

    if (( CURRENT == 2 )); then
        _describe 'netcheck command' subcmds
        return
    fi

    case "${words[2]}" in
        completion)
            if (( CURRENT == 3 )); then
                _values 'shell' bash zsh fish powershell
            fi
            ;;
        *)
            # For --output flag values, complete the four formats.
            if [[ "${words[CURRENT-1]}" == "--output" || "${words[CURRENT-1]}" == "-output" ]]; then
                _values 'output format' text json markdown html
                return
            fi
            _files
            ;;
    esac
}

compdef _netcheck netcheck
`

// fishCompletion: per-subcommand `complete` lines. Each gets a description
// that fish shows in its completion pager.
var fishCompletion = `# fish completion for netcheck — generated by ` + "`netcheck completion fish`" + `

complete -c netcheck -f

# Top-level subcommands (only offered when no subcommand has been entered yet).
complete -c netcheck -n '__fish_use_subcommand' -a menu       -d 'interactive menu'
complete -c netcheck -n '__fish_use_subcommand' -a app        -d 'run the local web app'
complete -c netcheck -n '__fish_use_subcommand' -a dns        -d 'compare DNS resolvers'
complete -c netcheck -n '__fish_use_subcommand' -a route      -d 'trace the network path with per-hop ASN'
complete -c netcheck -n '__fish_use_subcommand' -a ip         -d 'IP ownership, RDAP, reverse DNS, CDN hints'
complete -c netcheck -n '__fish_use_subcommand' -a headers    -d 'security-header report card'
complete -c netcheck -n '__fish_use_subcommand' -a tech       -d 'fingerprint CMS / framework / server / CDN'
complete -c netcheck -n '__fish_use_subcommand' -a subs       -d 'enumerate subdomains via CT logs'
complete -c netcheck -n '__fish_use_subcommand' -a reverse    -d 'other hostnames on this IP'
complete -c netcheck -n '__fish_use_subcommand' -a arch       -d 'Wayback Machine snapshots'
complete -c netcheck -n '__fish_use_subcommand' -a whois      -d 'registrar lookup via RDAP'
complete -c netcheck -n '__fish_use_subcommand' -a tls        -d 'TLS protocol+cipher audit (ACTIVE)'
complete -c netcheck -n '__fish_use_subcommand' -a takeover   -d 'subdomain-takeover check (ACTIVE)'
complete -c netcheck -n '__fish_use_subcommand' -a ports      -d 'TCP connect scan (ACTIVE)'
complete -c netcheck -n '__fish_use_subcommand' -a enum       -d 'HTTP path enumeration (ACTIVE)'
complete -c netcheck -n '__fish_use_subcommand' -a audit      -d 'aggregate report (passive + optional active)'
complete -c netcheck -n '__fish_use_subcommand' -a config     -d 'print active config'
complete -c netcheck -n '__fish_use_subcommand' -a completion -d 'print shell completion script'
complete -c netcheck -n '__fish_use_subcommand' -a help       -d 'show help'
complete -c netcheck -n '__fish_use_subcommand' -a version    -d 'show version'

# completion <shell>
complete -c netcheck -n '__fish_seen_subcommand_from completion' -a 'bash zsh fish powershell'

# --output values for every leaf subcommand.
complete -c netcheck -l output -d 'output format' -xa 'text json markdown html'
complete -c netcheck -l config -d 'path to config file' -r
complete -c netcheck -l insecure -d 'skip TLS verification'
complete -c netcheck -l i-have-authorization -d 'consent flag for active scans'
`

// powershellCompletion: argument completer registered against the native
// `netcheck` command. PowerShell's completion model is closer to zsh than
// bash — every suggestion comes back as a CompletionResult with a tooltip.
var powershellCompletion = `# PowerShell completion for netcheck — generated by ` + "`netcheck completion powershell`" + `
# Add to $PROFILE to persist across sessions, or pipe through Invoke-Expression
# for one-shot setup.

Register-ArgumentCompleter -Native -CommandName netcheck -ScriptBlock {
    param($wordToComplete, $commandAst, $cursorPosition)

    $commands = @(
        @{ Name = 'menu';       Tooltip = 'interactive menu' }
        @{ Name = 'app';        Tooltip = 'run the local web app' }
        @{ Name = 'dns';        Tooltip = 'compare DNS resolvers' }
        @{ Name = 'route';      Tooltip = 'trace the network path with per-hop ASN' }
        @{ Name = 'ip';         Tooltip = 'IP ownership, RDAP, reverse DNS, CDN hints' }
        @{ Name = 'headers';    Tooltip = 'security-header report card' }
        @{ Name = 'tech';       Tooltip = 'fingerprint CMS / framework / server / CDN' }
        @{ Name = 'subs';       Tooltip = 'enumerate subdomains via CT logs' }
        @{ Name = 'reverse';    Tooltip = 'other hostnames on this IP' }
        @{ Name = 'arch';       Tooltip = 'Wayback Machine snapshots' }
        @{ Name = 'whois';      Tooltip = 'registrar lookup via RDAP' }
        @{ Name = 'tls';        Tooltip = 'TLS protocol+cipher audit (ACTIVE)' }
        @{ Name = 'takeover';   Tooltip = 'subdomain-takeover check (ACTIVE)' }
        @{ Name = 'ports';      Tooltip = 'TCP connect scan (ACTIVE)' }
        @{ Name = 'enum';       Tooltip = 'HTTP path enumeration (ACTIVE)' }
        @{ Name = 'audit';      Tooltip = 'aggregate report (passive + optional active)' }
        @{ Name = 'config';     Tooltip = 'print active config' }
        @{ Name = 'completion'; Tooltip = 'print shell completion script' }
        @{ Name = 'help';       Tooltip = 'show help' }
        @{ Name = 'version';    Tooltip = 'show version' }
    )

    # Tokenize what the user has typed so far. Element 0 is "netcheck".
    $tokens = $commandAst.CommandElements | ForEach-Object { $_.ToString() }

    if ($tokens.Count -le 2) {
        # Completing the first positional — the subcommand name.
        $commands |
            Where-Object { $_.Name -like "$wordToComplete*" } |
            ForEach-Object {
                [System.Management.Automation.CompletionResult]::new(
                    $_.Name, $_.Name, 'ParameterValue', $_.Tooltip
                )
            }
        return
    }

    if ($tokens[1] -eq 'completion' -and $tokens.Count -le 3) {
        @('bash', 'zsh', 'fish', 'powershell') |
            Where-Object { $_ -like "$wordToComplete*" } |
            ForEach-Object {
                [System.Management.Automation.CompletionResult]::new(
                    $_, $_, 'ParameterValue', "shell: $_"
                )
            }
        return
    }

    # --output values.
    $prev = if ($tokens.Count -ge 2) { $tokens[-2] } else { '' }
    if ($prev -eq '--output' -or $prev -eq '-output') {
        @('text', 'json', 'markdown', 'html') |
            Where-Object { $_ -like "$wordToComplete*" } |
            ForEach-Object {
                [System.Management.Automation.CompletionResult]::new(
                    $_, $_, 'ParameterValue', "output format: $_"
                )
            }
    }
}
`
